# ==============================================================================
# Este Dockerfile cria uma imagem para uso no Workshop da UnBeatables
# ------------------------------------------------------------------------------
# Também instala nessa imagem o software Choregraphe da Softbank Robotics
# que deve ser baixado separadamente com a devida licença para instalação
# ==============================================================================

FROM unbeatables

ENV   BUILD_DATE 2019-05-15
LABEL Maintainer="Lívia Fonseca (liviagcf@gmail.com)" \
      Description="Container 'unbeatables' com Softbank's Choregraphe Suite"

USER 0

ARG CHOREGRAPHE

ADD $CHOREGRAPHE $INSTALL_SCRIPTS/
COPY choregraphe.sh $INSTALL_SCRIPTS
COPY avahi.sh $INIT_DIR/startup.d/
COPY *.desktop /usr/share/applications/

RUN chmod a+x $INIT_DIR/startup.d/avahi.sh
RUN find $INSTALL_SCRIPTS -name '*.sh' -exec chmod a+x {} +
RUN $INSTALL_SCRIPTS/choregraphe.sh

RUN rm -f $INSTALL_SCRIPTS/*

USER 1000

VOLUME $HOME/Projetos
