#!/bin/bash

USER_ID=$(id -u)
GROUP_ID=$(id -g)

echo "USER_ID: $USER_ID, GROUP_ID: $GROUP_ID"

if [ x"$USER_ID" != x"0" ]; then

    NSS_WRAPPER_PASSWD=/tmp/passwd
    NSS_WRAPPER_GROUP=/etc/group

    cat /etc/passwd > $NSS_WRAPPER_PASSWD

    echo "unb:x:${USER_ID}:${GROUP_ID}:UnBeatables:${HOME}:/bin/bash" >> $NSS_WRAPPER_PASSWD

    export NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_GROUP
    [ -z "$USER" ] && export USER=unb

    if [ -r /usr/lib/libnss_wrapper.so ]; then
        LD_PRELOAD=/usr/lib/libnss_wrapper.so
    elif [ -r /usr/lib64/libnss_wrapper.so ]; then
        LD_PRELOAD=/usr/lib64/libnss_wrapper.so
    else
        echo "libnss_wrapper.so não instalado"
        exit 100
    fi
    export LD_PRELOAD
fi
